title: "[Help Needed] - Brief Summary of Your Issue"
labels: ["help request"]
body:
  - type: markdown
    attributes:
      value: |
        ## **Welcome! 👋**  
        We're here to help! Complete this form to make it easier for us to understand and solve your issue.  
        
  - type: dropdown
    id: topic
    attributes:
      label: What is your issue related to? (Select one)
      description: "Choose the category that best describes your issue."
      options:
        - Frontend (HTML, CSS, JavaScript, React)
        - Backend (Python, Django, SQL, etc.)
        - Tooling (Git/GitHub, VSCode, etc.)
        - Deployment/Hosting
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Describe Your Issue
      description: "Briefly describe your problem. Example: 'When I click the button, nothing happens. The console shows an error about a missing function.'"
      placeholder: "Enter your issue here"
    validations:
      required: true

  - type: textarea
    id: steps-tried
    attributes:
      label: What Have You Tried? 🧠
      description: "List steps you’ve already attempted. Example: 'Checked console logs and added error handling.'"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What Are You Expecting to Happen?
      description: "Describe the outcome you're aiming for. Example: 'Clicking the button should update the UI.'"
    validations:
      required: true

  - type: dropdown
    id: error-check
    attributes:
      label: Did You Check for Errors? (Console or Terminal)
      options:
        - Yes, I found errors (add details below)
        - Yes, but no errors appeared
        - No, I didn’t check (please check before submitting!)
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console/Terminal Error Messages
      description: "Paste any error messages. Use N/A if none apply."
      placeholder: "Enter error messages or N/A"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Research and Resources 🔍  
        Have you researched your issue? Add up to 3 helpful resources you found.  
        *Note: Research is optional but encouraged to improve your problem-solving skills!*

  - type: input
    id: resource-1
    attributes:
      label: Research Link 1
      description: "Paste a helpful link and explain why it’s relevant."
      placeholder: "e.g., Stack Overflow, MDN Docs"
    validations:
      required: false

  - type: input
    id: resource-2
    attributes:
      label: Research Link 2 (Optional)
      description: "Add another useful link."
    validations:
      required: false

  - type: input
    id: resource-3
    attributes:
      label: Research Link 3 (Optional)
      description: "Add a third useful link."
    validations:
      required: false

  - type: textarea
    id: code-link
    attributes:
      label: Share Your Code
      description: "Provide a **direct link** to the GitHub file causing the issue (not the whole repo)."
      placeholder: "e.g., https://github.com/username/repo/blob/main/file.js"
    validations:
      required: true

  - type: markdown
      attributes:
        value: |
          ## **Before Submitting:**  
          - ✅ Have you searched similar tickets or resources?  
          - ✅ Is your title descriptive and specific to your TECH issue?  
  
          ### REMONDER: Our team reviews requests within **48 hours**.


  
