body:
  - type: markdown
    attributes:
      value: |
        **Welcome! 👋**  
        We're here to help, and by answering these questions, you'll help us understand your problem faster and also learn some valuable problem-solving skills along the way!  
        **Make sure you're using this Help Discussion for technical issues.**

  - type: checkboxes
    attributes:
      label: "Have you searched other help tickets? If not, please do that first. 🕵️‍♂️"
      options:
        - label: "YES, I have"
          required: true

  - type: checkboxes
    attributes:
      label: "Is your title descriptive and related to the TECH issue, not just your project name?"
      options:
        - label: "YES"
          required: true

  - type: markdown
    attributes:
      value: |
        ## Describing Your Problem 🤔  
        This section helps you practice explaining technical issues clearly—a crucial skill for your tech career!
        In this section, you may use video like [Loom](https://www.loom.com/) or [Veed](https://www.veed.io/) if writing is difficult for you.
        **VIDEOS SHOULD BE 5 MINUTES OR LESS**

        ### LEARNING OBJECTIVE(S):  
        - Build your technical vocabulary  
        - Practice using debugging and developer tools  
        - Learn how to ask for help effectively

  - type: textarea
    id: issue
    attributes:
      label: "Describe your issue (Example below)"
      description: "Tell us what's happening. Example: 'When I click the button, nothing happens. The console shows an error about a missing function.'"
      placeholder: "Add your description here"
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: "What have you tried? 🧠 (Example below)"
      description: "Tell us what you have already attempted. Example: 'I added console logs and checked the console, but I'm still confused about the error.'"
    validations:
      required: true
    
  - type: textarea
    id: expect
    attributes:
      label: "What are you expecting to happen?"
      description: "Tell us what you want to happen."
    validations:
      required: true

  - type: dropdown
    id: console
    attributes:
      label: "Check your console or terminal for errors. Select the option that applies:"
      options:
        - I did not check my console/terminal for errors (THIS IS THE WRONG ANSWER)
        - My console/terminal has no errors
        - My console/terminal has errors I am providing below
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: "Console Error Messages"
      description: "List/type any error messages. (Screenshots can be useful too!)"
      placeholder: "Use N/A if this doesn't apply. To post code, use three backticks (``` before and after your code block)"
      render: bash
    validations:
      required: true

  - type: textarea
    id: network-tab
    attributes:
      label: "Did you check your network tab in dev tools (for data issues)? What did you find?"
      description: "Provide response and preview data if applicable. Use N/A if this doesn’t apply."
      placeholder: "To post code, use three backticks (``` before and after your code block)"
      render: bash
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Research and Resources 🔍  
        Learning to search for solutions is half the battle! Let's refine your searching skills and build your knowledge.  

        ### LEARNING OBJECTIVE(S):  
        - Improve your ability to research code issues and errors  
        - Refine search techniques for better results

  - type: input
    id: link-one
    attributes:
      label: "Research Link 1 (A helpful resource you found)"
      description: "Paste a useful link from your research and explain why it helped."
    validations:
      required: true

  - type: input
    id: link-two
    attributes:
      label: "Research Link 2 (Another helpful resource)"
      description: "Paste another helpful link and explain how it supports your issue."
    validations:
      required: true

  - type: input
    id: link-three
    attributes:
      label: "Research Link 3 (Another helpful resource)"
      description: "Paste a third helpful link and explain how it supports your issue."
    validations:
      required: true

  - type: textarea
    id: link-explanations
    attributes:
      label: "Links Explanation"
      description: "What did you learn from all of the resource/links you listed above?"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Share Your Code 💻  
        We need to see the actual code causing the issue, so **no screenshots** please! Share the GitHub file link. 
        [Use this ticket if you need help](https://github.com/orgs/nss-evening-web-development/discussions/1174).

        ### LEARNING OBJECTIVE(S):  
        - Learn to share your code effectively using GitHub  
        - Identify specific issues in your code more easily

  - type: textarea
    id: repo-links
    attributes:
      label: "GitHub FILE links - DO NOT PUT A LINK TO YOUR WHOLE REPO."
      description: "Share a link to the specific file (not the whole repo) where you need help. We will not review requests that do not submit links to the impacted files."
    validations:
      required: true
